### ISSUE TITLE
 E tensorflow/stream_executor/cuda/cuda_blas.cc:654] failed to run cuBLAS routine cublasDgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by star5o** [tsc2017/Frechet-Inception-Distance#3]
## When I run the program, I get  this error:
`2019-04-19 21:16:23.177552: E tensorflow/stream_executor/cuda/cuda_blas.cc:654] failed to run cuBLAS routine cublasDgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "/home/iie/.conda/envs/env36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/iie/.conda/envs/env36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/iie/.conda/envs/env36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(2048, 2048), b.shape=(2048, 2048), m=2048, n=2048, k=2048
	 [[Node: MatMul_6 = MatMul[T=DT_DOUBLE, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Svd_1:1, Diag_1)]]
`
### what should I do?
@tsc2017

**Comment by tsc2017** [comment]
Can you tell me which line of `fid.py` fails?  I cannot pinpoint the problem with the above information.
